@icon("res://addons/godot_gameplay_systems/attributes_and_abilities/assets/GameplayEffect.svg")
@tool
class_name GameplayEffect extends Node


@export_category("Effect")
## Is the [AttributeTable] resource
@export var table: AttributeTable = null
## Is the array of [AttributeEffect] resources generated by the inspector
@export var attributes_affected: Array[AttributeEffect] = []
